// Auto-generated by scripts/build-templates.ts — DO NOT EDIT
// Regenerate with: npx tsx scripts/build-templates.ts

export const templates: Record<string, string> = {
  "archive-articles": `<section class="section archive archive--articles">
    <div class="container">
        <% if (archive.title) { %>
            <div class="content">
                <h2 class="h4"><%= archive.title %></h2>
            </div>
        <% } %>
        <ul class="archive-grid">
            <% archive.children.forEach(function(item) { %>
                <li class="archive-card" style="<%= item.meta.sectionStyle || '' %>">
                    <a class="archive-card__link" href="<%= item.redirect || item.link %>">
                        <% if (item.icon) { %>
                            <%- renderIcon(item.icon, 'archive-card__media archive-card__media--icon', 'archive-card__icon') %>
                        <% } %>
                        <div class="archive-card__body">
                            <h3 class="archive-card__title"><%= item.title %></h3>
                            <% if (item.excerpt) { %>
                                <p class="archive-card__excerpt"><%- item.excerpt %></p>
                            <% } %>
                        </div>
                    </a>
                </li>
            <% }) %>
        </ul>
    </div>
</section>
`,
  "archive-blog": `<section class="section archive archive--blog">
    <div class="container">
        <ul class="archive-grid archive-grid--blog">
            <% archive.children.forEach(function(item) { %>
                <li class="archive-card archive-card--blog" style="<%= item.meta.sectionStyle || '' %>">
                    <a class="archive-card__link" href="<%= item.redirect || item.link %>">
                        <% if (item.thumbnail) { %>
                            <span class="archive-card__media archive-card__media--image">
                                <img class="archive-card__image" src="<%= item.thumbnail %>" alt="">
                            </span>
                        <% } %>
                        <div class="archive-card__body">
                            <% if (item.date) { %>
                                <p class="archive-card__meta"><%= formatDate(item.date, "dd MMM yyyy") %></p>
                            <% } %>
                            <h3 class="archive-card__title"><%= item.title %></h3>
                            <% if (item.excerpt) { %>
                                <p class="archive-card__excerpt"><%- item.excerpt %></p>
                            <% } %>
                        </div>
                    </a>
                </li>
            <% }) %>
        </ul>
    </div>
</section>
`,
  "archive-collection": `<section class="section archive--collection">
    <div class="container">
        <div class="content"></div>
        <% archive.children.forEach(function(item) { %>
            <%- item.html %>
        <% }) %>
    </div>
</section>
`,
  "archive-section": `<% archive.children.forEach(function(item) { %>
    <section class="section archive-item archive--section" style="<%= item.meta.sectionStyle || '' %>" id="<%= item.id %>">
        <div class="container">
            <div class="content">
                <%- item.html %>
            </div>
        </div>
    </section>
<% }) %>
`,
  "archive": `<% archives.forEach(function(archive) { %>
    <% if (archive.type === 'sections') { %>
        <%- partials['archive-section']({ archive: archive }) %>
    <% } else if (archive.type === 'collection') { %>
        <%- partials['archive-collection']({ archive: archive }) %>
    <% } else if (archive.type === 'blog') { %>
        <%- partials['archive-blog']({ archive: archive, formatDate: formatDate }) %>
    <% } else if (archive.type === 'articles') { %>
        <%- partials['archive-articles']({ archive: archive, renderIcon: renderIcon }) %>
    <% } %>
<% }) %>
`,
  "content": `<main class="main<%= meta.type ? ' content--' + meta.type : '' %>">
    <section class="section" style="<%= meta.sectionStyle || '' %>">
        <div class="container">
            <div class="content">
                <% if (subtitle) { %>
                    <h6><%= subtitle %></h6>
                <% } %>
                <% if (showContentImage) { %>
                    <h1><%= title %></h1>
                    <figure>
                        <img src="<%= meta.image %>">
                    </figure>
                    <%- removeTitle(content) %>
                <% } else { %>
                    <%- content %>
                <% } %>
            </div>
        </div>
    </section>

    <% if (relatedPages && relatedPages.length) { %>
        <section class="section section--related">
            <div class="container">
                <div class="content">
                    <% if (parentPage) { %>
                        <h6><%= parentPage.title %></h6>
                    <% } %>
                    <h2>More Pages</h2>
                </div>
                <ul class="archive-grid">
                    <% relatedPages.forEach(function(item) { %>
                        <li class="archive-card" style="<%= item.meta.sectionStyle || '' %>">
                            <a class="archive-card__link" href="<%= item.redirect || item.link %>">
                                <% if (item.icon) { %>
                                    <%- renderIcon(item.icon, 'archive-card__media archive-card__media--icon', 'archive-card__icon') %>
                                <% } %>
                                <div class="archive-card__body">
                                    <h3 class="archive-card__title"><%= item.title %></h3>
                                    <% if (item.excerpt) { %>
                                        <p class="archive-card__excerpt"><%- item.excerpt %></p>
                                    <% } %>
                                </div>
                            </a>
                        </li>
                    <% }) %>
                </ul>
            </div>
        </section>
    <% } %>

    <% if (archives.length) { %>
        <%- partials.archive({ archives: archives, formatDate: formatDate, renderIcon: renderIcon, partials: partials }) %>
    <% } %>

    <% if (tags.length) { %>
        <%- partials.tags({ tags: tags }) %>
    <% } %>
</main>
`,
  "footer": `<%
  function renderColorModeToggle() {
    return '<div class="footer__control">' +
      '<button class="color-mode-toggle" type="button" data-color-mode-toggle aria-label="Toggle color mode" aria-pressed="false">' +
        '<span class="color-mode-toggle__option" aria-hidden="true">' +
          '<span class="color-mode-toggle__icon">' +
            '<svg class="color-mode-toggle__icon-asset" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">' +
              '<circle cx="12" cy="12" r="4"></circle>' +
              '<line x1="12" y1="1.5" x2="12" y2="4"></line>' +
              '<line x1="12" y1="20" x2="12" y2="22.5"></line>' +
              '<line x1="4.22" y1="4.22" x2="5.98" y2="5.98"></line>' +
              '<line x1="18.02" y1="18.02" x2="19.78" y2="19.78"></line>' +
              '<line x1="1.5" y1="12" x2="4" y2="12"></line>' +
              '<line x1="20" y1="12" x2="22.5" y2="12"></line>' +
              '<line x1="4.22" y1="19.78" x2="5.98" y2="18.02"></line>' +
              '<line x1="18.02" y1="5.98" x2="19.78" y2="4.22"></line>' +
            '</svg>' +
          '</span>' +
          '<span class="color-mode-toggle__track" aria-hidden="true">' +
            '<span class="color-mode-toggle__thumb"></span>' +
          '</span>' +
          '<span class="color-mode-toggle__option" aria-hidden="true">' +
            '<span class="color-mode-toggle__icon">' +
              '<svg class="color-mode-toggle__icon-asset" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">' +
                '<path d="M20.5 14.5A8.5 8.5 0 1 1 9.5 3.5a6.5 6.5 0 0 0 11 11Z"></path>' +
              '</svg>' +
            '</span>' +
          '</span>' +
        '</button>' +
      '</div>';
  }

  function renderLanguageMenu(langMenu) {
    if (!langMenu || langMenu.length <= 1) return '';
    let out = '<div class="footer__control"><ul class="language">';
    langMenu.forEach(function(language) {
      out += '<li class="language__item' + (language.active ? ' language__item--active' : '') + '">' +
        '<a class="language__link" href="' + language.link + '" data-title="' + language.title + '" data-code="' + language.code + '" data-name="' + language.name + '">' +
          '<span class="language__text">' + language.code + '</span>' +
        '</a></li>';
    });
    out += '</ul></div>';
    return out;
  }
%>
<footer class="footer">
    <div class="footer__container">
        <% if (menu.length > 0) { %>
            <div class="footer__navigation">
                <%- partials.navigation({ menu: menu, variant: 'footer', navigationIdPrefix: 'footer-navigation', renderIcon: renderIcon }) %>
            </div>
        <% } %>

        <% if (logo || langMenu.length > 1) { %>
            <div class="footer__bar">
                <% if (logo) { %>
                    <div class="footer__brand">
                        <%- partials.logo({ project: project, logo: logo, homeLink: homeLink, logoVariant: 'footer' }) %>
                    </div>
                <% } %>
                <div class="footer__controls">
                    <%- renderLanguageMenu(langMenu) %>
                    <%- renderColorModeToggle() %>
                </div>
            </div>
        <% } else { %>
            <div class="footer__bar footer__bar--end">
                <div class="footer__controls">
                    <%- renderColorModeToggle() %>
                </div>
            </div>
        <% } %>

        <% if (config.copyright || (socials && socials.length)) { %>
            <div class="footer__meta">
                <% if (config.copyright) { %>
                    <div class="copyright">
                        <%- config.copyright %>
                    </div>
                <% } %>
                <% if (socials && socials.length) { %>
                    <ul class="socials">
                        <% socials.forEach(function(social) { %>
                            <li class="socials__item">
                                <a class="socials__link" href="<%= social.link %>" aria-label="<%= social.title %>" title="<%= social.title %>">
                                    <span class="socials__text"><%= social.title %></span>
                                </a>
                            </li>
                        <% }) %>
                    </ul>
                <% } %>
            </div>
        <% } %>
    </div>
</footer>

<% if (has.search) { %>
    <script src="/assets/search/client.js"></script>
<% } %>

<% if (project.script) { %>
    <% (Array.isArray(project.script) ? project.script : [project.script]).forEach(function(script) { %>
        <script lang="text/javascript"<% if (typeof script === 'object') { %> src="<%= script.src %>" type="<%= script.type %>"<% } else { %> src="<%= script %>"<% } %>></script>
    <% }) %>
<% } %>
`,
  "head": `<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="view-transition" content="same-origin">
    <% if (generator && generator.name && generator.version) { %>
        <meta name="generator" content="<%= generator.name %> <%= generator.version %>">
    <% } %>
    <% if (meta.redirect) { %>
        <meta http-equiv="refresh" content="0; url=<%= meta.redirect %>">
        <link rel="canonical" href="<%= meta.redirect %>">
    <% } %>
    <% if (meta.date) { %>
        <meta name="updated" content="<%= formatDate(meta.date, 'yy-MM-dd') %>">
    <% } %>

    <% if (type) { %>
        <meta name="type" content="<%= type %>">
    <% } %>

    <% if (meta.description) { %>
        <meta name="description" content="<%= meta.description %>">
    <% } else if (project.description) { %>
        <meta name="description" content="<%= project.description %>">
    <% } %>

    <% if (meta.title && project.title) { %>
        <title><%= meta.title %> | <%= project.title %></title>
    <% } else if (project.title) { %>
        <title><%= project.title %></title>
    <% } else if (meta.title) { %>
        <title><%= meta.title %></title>
    <% } else { %>
        <title><%= title %></title>
    <% } %>

    <% if (favicons) { %>
        <% if (favicons.light) { %>
            <link rel="icon" type="image/x-icon" href="/<%= favicons.light %>" media="(prefers-color-scheme: light)">
        <% } %>
        <% if (favicons.dark) { %>
            <link rel="icon" type="image/x-icon" href="/<%= favicons.dark %>" media="(prefers-color-scheme: dark)">
        <% } else if (favicons.default) { %>
            <link rel="icon" type="image/x-icon" href="/<%= favicons.default %>">
        <% } %>
    <% } %>

    <% if (style.path) { %>
        <link href="<%= style.path %>" rel="stylesheet" type="text/css">
    <% } %>

    <% if (config.styleCustom) { %>
        <link href="<%= config.styleCustom %>" rel="stylesheet" type="text/css">
    <% } %>

    <% if (style.add) { %>
        <link href="<%= style.add %>" rel="stylesheet" type="text/css">
    <% } %>

    <% if (meta.redirect) { %>
        <script>window.location.replace("<%= meta.redirect %>");</script>
    <% } %>
</head>`,
  "header": `<%
  let navigationVariant = 'header';
  let navigationIdPrefix = 'header-navigation';
%>
<header class="header">
    <div class="header__container">
        <%- partials.logo({ project: project, logo: logo, homeLink: homeLink, logoVariant: '' }) %>

        <% if (menu.length > 0) { %>
          <%- partials.navigation({ menu: menu, variant: 'header', navigationIdPrefix: 'header-navigation', renderIcon: renderIcon }) %>
        <% } %>

        <% if (has.search) { %>
            <div class="header__actions">
                <button class="search-toggle" type="button" aria-label="Open search" aria-haspopup="dialog" aria-controls="site-search" aria-expanded="false" data-search-open>
                    <span class="search-toggle__icon" aria-hidden="true">
                        <svg class="search-toggle__icon-asset" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
                            <circle cx="11" cy="11" r="6.5"></circle>
                            <line x1="16" y1="16" x2="21" y2="21"></line>
                        </svg>
                    </span>
                </button>
            </div>
        <% } %>
    </div>
</header>`,
  "icon": `<%
// renderIcon is provided as a template variable from render.ts.
// It is no longer defined inline — this template is kept for
// backwards compatibility as a no-op partial.
%>
`,
  "logo": `<%
  var logoVariant = typeof logoVariant !== 'undefined' ? logoVariant : '';
  const variant = logoVariant ? ' logo--' + logoVariant : '';
%>
<% if (project) { %>
  <% if (logo) { %>
    <% if (logo.data) { %>
      <a class="logo<%= variant %> logo--image-only" href="<%= homeLink %>" aria-label="<%= project.title %>"><%- logo.data %></a>
    <% } else if (logo.relativePath) { %>
      <a class="logo<%= variant %>" href="<%= homeLink %>" aria-label="<%= project.title %>"><img src="<%= logo.relativePath %>"></a>
    <% } %>
  <% } else if (project.title) { %>
    <a class="logo logo--title<%= variant %>" href="<%= homeLink %>"><span class="logo__text"><%= project.title %></span></a>
  <% } %>
<% } %>`,
  "navigation": `<%
  var navigationRoot = typeof navigationIdPrefix !== 'undefined' ? navigationIdPrefix : 'navigation';
  var variant = typeof navigationVariant !== 'undefined' ? navigationVariant : 'header';

  function renderPanelGroups(items, level) {
    const compactColumnClass = level === 1 && items.length <= 5 ? ' navigation__groups--compact-column' : '';
    let out = '<ul class="navigation__groups navigation__groups--level-' + level + compactColumnClass + '">';
    items.forEach(function(item) {
      const hasChildren = !!(item.children && item.children.length);
      out += '<li class="navigation__group' +
        (hasChildren ? ' navigation__group--branch' : ' navigation__group--leaf') +
        (item.current ? ' navigation__group--current' : '') +
        (item.isParent ? ' navigation__group--parent' : '') + '">';
      out += '<a class="navigation__group-link' + (hasChildren ? ' navigation__group-link--heading' : '') + '" href="' + item.link + '">';
      out += renderIcon(item.icon, 'navigation__icon', 'navigation__icon-asset');
      out += '<span class="navigation__text">' + item.name + '</span></a>';
      if (hasChildren) {
        out += renderPanelGroups(item.children, level + 1);
      }
      out += '</li>';
    });
    out += '</ul>';
    return out;
  }

  function renderHeaderNavigation(items) {
    let out = '<span class="navigation__active-pill" aria-hidden="true"></span>';
    out += '<ul class="navigation__list" id="' + navigationRoot + '-list">';
    items.forEach(function(item, index) {
      const hasChildren = !!(item.children && item.children.length);
      const isOpen = false;
      const panelId = navigationRoot + '-panel-' + index;
      const panelAnchor = '--' + navigationRoot + '-panel-anchor-' + index;
      out += '<li class="navigation__item' +
        (item.current ? ' navigation__item--current' : '') +
        (item.isParent && !item.current ? ' navigation__item--parent' : '') +
        (hasChildren ? ' navigation__item--has-children' : '') +
        (isOpen ? ' navigation__item--open' : '') + '">';
      out += '<div class="navigation__entry"' + (hasChildren ? ' style="anchor-name: ' + panelAnchor + ';"' : '') + '>';
      out += '<a class="navigation__link" href="' + item.link + '">';
      out += renderIcon(item.icon, 'navigation__icon', 'navigation__icon-asset');
      out += '<span class="navigation__text">' + item.name + '</span></a>';
      if (hasChildren) {
        out += '<button class="navigation__toggle" type="button" aria-expanded="' + (isOpen ? 'true' : 'false') + '" aria-controls="' + panelId + '" aria-haspopup="true" aria-label="Toggle ' + item.name + ' submenu"></button>';
      }
      out += '</div>';
      if (hasChildren) {
        out += '<div class="navigation__panel" id="' + panelId + '"' + (!isOpen ? ' hidden' : '') + ' style="position-anchor: ' + panelAnchor + ';">';
        out += '<div class="navigation__panel-inner">';
        out += renderPanelGroups(item.children, 1);
        out += '</div></div>';
      }
      out += '</li>';
    });
    out += '</ul>';
    return out;
  }

  function renderFooterTree(items, level) {
    let out = '<ul class="navigation__footer-list navigation__footer-list--level-' + level + '">';
    items.forEach(function(item) {
      const hasChildren = !!(item.children && item.children.length);
      out += '<li class="navigation__footer-item' +
        (item.current ? ' navigation__footer-item--current' : '') +
        (item.isParent ? ' navigation__footer-item--parent' : '') +
        (hasChildren ? ' navigation__footer-item--branch' : '') + '">';
      out += '<a class="navigation__footer-link' + (level === 0 ? ' navigation__footer-link--heading' : '') + '" href="' + item.link + '">';
      out += renderIcon(item.icon, 'navigation__icon', 'navigation__icon-asset');
      out += '<span class="navigation__text">' + item.name + '</span></a>';
      if (hasChildren) {
        out += renderFooterTree(item.children, level + 1);
      }
      out += '</li>';
    });
    out += '</ul>';
    return out;
  }
%>
<% if (variant === 'footer') { %>
  <nav class="navigation navigation--footer">
    <%- renderFooterTree(menu, 0) %>
  </nav>
<% } else { %>
  <%
    const hasNestedChildren = menu.some(function(item) { return item.children && item.children.length; });
    const useMobilePanel = menu.length > 2 || hasNestedChildren;
    const mobileMode = useMobilePanel ? 'panel' : 'inline';
  %>
  <nav class="navigation navigation--header<%= useMobilePanel ? ' navigation--mobile-panel' : ' navigation--mobile-inline' %>" data-mobile-mode="<%= mobileMode %>">
    <% if (useMobilePanel) { %>
      <button class="navigation__mobile-toggle" type="button" aria-expanded="false" aria-controls="<%= navigationRoot %>-list" aria-label="Toggle navigation menu" style="anchor-name: --<%= navigationRoot %>-mobile-toggle;">
        <span class="navigation__mobile-toggle-icon" aria-hidden="true"></span>
        <span class="navigation__mobile-toggle-label">Menu</span>
      </button>
    <% } %>
    <%- renderHeaderNavigation(menu) %>
  </nav>
<% } %>`,
  "page": `<!DOCTYPE html>
<html lang="<%= language %>">
<%- partials.head(data) %>

<body class="page--<%= name %>">
    <div class="page-container">
        <%- partials.header({ project: project, logo: logo, menu: menu, homeLink: homeLink, has: has, renderIcon: renderIcon, partials: partials }) %>
        <%- partials.content({ content: content, title: title, name: name, meta: meta, subtitle: subtitle, showContentImage: showContentImage, removeTitle: removeTitle, relatedPages: relatedPages, parentPage: parentPage, archives: archives, tags: tags, formatDate: formatDate, renderIcon: renderIcon, partials: partials }) %>
    </div>

    <%- partials.footer({ project: project, logo: logo, menu: menu, homeLink: homeLink, has: has, config: config, socials: socials, langMenu: langMenu, renderIcon: renderIcon, partials: partials }) %>

    <%- partials.search({ has: has, searchContext: searchContext }) %>

    <script>
        <% if (has.header) { %>
            <%- scripts.navigation %>
        <% } %>
        <%- scripts.colorMode %>
        <% if (has.languages) { %>
            <%- scripts.detectLanguage %>
        <% } %>
        <% if (has.colors) { %>
            <%- scripts.findColors %>
        <% } %>
        <% if (has.table) { %>
            <%- scripts.wrapTables %>
        <% } %>
        <% if (has.urlToken) { %>
            <%- scripts.linkify %>
        <% } %>
    </script>
</body>
</html>
`,
  "search": `<% if (has.search) { %>
    <div class="search-shell" hidden data-search-shell>
        <button class="search-shell__backdrop" type="button" aria-label="Close search" data-search-close tabindex="-1"></button>
        <div class="search-shell__dialog"
            id="site-search"
            role="dialog"
            aria-modal="true"
            aria-labelledby="site-search-title"
            data-search-scope="<%= searchContext.scope %>"
            data-search-page-id="<%= searchContext.pageId %>"
            data-search-branch="<%= searchContext.branch %>"
            data-search-dialog
        >
            <form class="search-shell__panel" role="search" novalidate data-search-form>
                <h2 class="search-shell__title" id="site-search-title">Search</h2>
                <label class="search-shell__field" for="site-search-input">
                    <span class="search-shell__field-icon" aria-hidden="true">
                        <svg class="search-shell__field-icon-asset" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
                            <circle cx="11" cy="11" r="6.5"></circle>
                            <line x1="16" y1="16" x2="21" y2="21"></line>
                        </svg>
                    </span>
                    <input id="site-search-input" class="search-shell__input"
                        type="search"
                        autocomplete="off"
                        autocapitalize="off"
                        spellcheck="false"
                        placeholder="Search this site"
                        enterkeyhint="search"
                        data-search-input
                    >
                    <button class="search-shell__close" type="button" aria-label="Close search" data-search-close>
                        <span class="search-shell__close-icon" aria-hidden="true"></span>
                    </button>
                </label>
                <p class="search-shell__hint">Search pages in this site. Results update while you type.</p>
                <div class="search-shell__results search-results" data-search-results hidden></div>
            </form>
        </div>
    </div>
<% } %>`,
  "tags": `<section class="section tags">
    <ul class="tag__list">
        <% tags.forEach(function(tag) { %>
            <li class="tag__item">
                <a class="tag__link" href="<%= tag.link %>">
                    <span class="tag__text"><%= tag.name %></span>
                </a>
            </li>
        <% }) %>
    </ul>
</section>
`,
};

export const scripts: Record<string, string> = {
  "colorMode": `const isDarkMode = window.matchMedia("prefers-color-scheme: dark").matches;
let localMode = isDarkMode ? "dark" : "light";

const updateColorModeToggle = () => {
  const toggle = document.querySelector("[data-color-mode-toggle]");
  if (!toggle) return;

  toggle.dataset.colorMode = localMode;
  toggle.setAttribute("aria-pressed", localMode === "dark" ? "true" : "false");
  toggle.setAttribute(
    "aria-label",
    localMode === "dark" ? "Switch to light mode" : "Switch to dark mode"
  );
};

const initColorMode = () => {
  localMode = localStorage.getItem("colorMode");
  setCurrentMode(localMode ? localMode : isDarkMode ? "dark" : "light");
};

const setCurrentMode = (mode) => {
  localMode = mode;
  localStorage.setItem("colorMode", localMode);
  document.documentElement.setAttribute("color-mode", mode);
  document.body.setAttribute("color-mode", mode);
  updateColorModeToggle();
};

const switchMode = () => {
  if (localMode == "dark") setCurrentMode("light");
  else setCurrentMode("dark");
};

const bindColorModeToggle = () => {
  const toggle = document.querySelector("[data-color-mode-toggle]");
  if (!toggle) return;

  toggle.addEventListener("click", () => {
    switchMode();
  });
};

initColorMode();
bindColorModeToggle();
`,
  "detectLanguage": `const languageElements = document.querySelectorAll(".language__item");
const languages = [];

const getBrowserLanguage = () => {
  const language = window.navigator.userLanguage || window.navigator.language;

  if (language.includes("-")) return language.split("-")[0];

  return language;
};

const getCurrentLanguage = () => {
  const local = localStorage.getItem("currentLanguage");
  const language = document.documentElement.lang;
  return local || language;
};

languageElements.forEach((l) => {
  const link = l.querySelector(".language__link");
  languages.push({
    element: l,
    code: link.getAttribute("data-code"),
    title: link.getAttribute("data-title"),
    name: link.getAttribute("data-name"),
    link: link.getAttribute("href"),
  });
});

const setLanguage = () => {
  // If there is only one language, it doesn't make sense.
  if (Object.keys(languages).length < 2) return;
  
  // If the current language, is already the prefered language.
  if (getBrowserLanguage() == getCurrentLanguage()) return;

  // Check if the prefered language, exists in our list.
  const lang = languages.find((l) => l.code == getBrowserLanguage());

  if (lang) window.location.replace(\`\${window.location.origin}\${lang.link}\`);

  return;
};

const setLocalLanguage = (code) => {
  localStorage.setItem("language", code);
};

const init = () => {
  languages.forEach((lang) => {
    lang.element.addEventListener("click", (e) => {
      setLocalLanguage(lang.code);
    });
  });
};

init();
`,
  "findColors": `const container = document.querySelector(".container").querySelectorAll("*");

container.forEach((el) => {
  const text = el.innerText;
  if (el.innerHTML == el.textContent)
    if (text) {
      const matches = text.match(/#[a-fA-F0-9]{6}|#[a-fA-F0-9]{3}/i);
      if (matches) {
        el.innerHTML = el.innerHTML.replace(
          matches[0],
          \`<span class="color-preview" style="--color-preview:\${matches[0]}">\${matches[0]}</span>\`
        );
      }
    }
});
`,
  "headerNavigation": `const setHovers = () => {

  const navigationLinks = document.querySelectorAll(
    ".header .navigation__link"
  );

  let hovering = null;

  navigationLinks.forEach((link) => {
    link.addEventListener("mouseover", (e) => {
      if (hovering == link) return;
      const sizes = e.target.getBoundingClientRect();
      const navigation = document.querySelector(".header .navigation__list");
      const navigationSizes = navigation.getBoundingClientRect();

      const x = \`\${Math.round(sizes.left - navigationSizes.left)}px\`;
      const w = \`\${Math.round(sizes.width)}px\`;

      navigation.style.setProperty("--h-w", w);
      navigation.style.setProperty("--h-x", x);
      hovering = link;
    });
  });
};

const setCurrent = () => {
  const currentLink = document.querySelector(
    ".header .navigation__item--current"
  );

  if (!currentLink) return;

  const linkSize = currentLink.getBoundingClientRect();
  const navigation = document.querySelector(".header .navigation");
  const navigationSize = document
    .querySelector(".header .navigation__list")
    .getBoundingClientRect();

  const x = \`\${Math.round(linkSize.left - navigationSize.left)}px\`;
  const w = \`\${Math.round(linkSize.width)}px\`;
  navigation.style.setProperty("--x", x);
  navigation.style.setProperty("--w", w);
  navigation.setAttribute("data-x", x);
  navigation.setAttribute("data-w", w);
};

const initNavigation = () => {
  setHovers();
  setCurrent();
};
initNavigation();
`,
  "linkify": `const urlTokens = document.querySelectorAll(".token.url");

urlTokens.forEach((token) => {
  if (token.innerHTML == token.textContent) {
    const text = token.textContent;

    if (text.includes("http")) {
      const link = document.createElement("a");
      link.setAttribute("href", text);
      link.innerText = text;

      token.parentNode.replaceChild(link, token);
    }
  }
});
`,
  "navigation": `const getNavigationItems = (navigation) =>
  Array.from(
    navigation.querySelectorAll(".navigation__item--has-children")
  );

const PANEL_TRANSITION_MS = 180;
const DESKTOP_NAVIGATION_MEDIA = "(min-width: 961px)";

const clearPanelHideTimer = (submenu) => {
  if (!submenu || typeof submenu.__hideTimer !== "number") return;

  window.clearTimeout(submenu.__hideTimer);
  delete submenu.__hideTimer;
};

const setNavigationItemPanelAlignment = (item) => {
  const toggle = item.querySelector(".navigation__toggle");
  const controls = toggle?.getAttribute("aria-controls");
  const submenu = controls ? document.getElementById(controls) : null;

  item.classList.remove("navigation__item--align-end");

  if (!submenu || !window.matchMedia(DESKTOP_NAVIGATION_MEDIA).matches) return;

  const gutter = 16;
  const submenuRect = submenu.getBoundingClientRect();

  if (submenuRect.right > window.innerWidth - gutter) {
    item.classList.add("navigation__item--align-end");
  }

  if (!item.classList.contains("navigation__item--align-end")) return;

  const alignedRect = submenu.getBoundingClientRect();
  if (alignedRect.left < gutter) {
    item.classList.remove("navigation__item--align-end");
  }
};

const setNavigationItemOpen = (item, isOpen) => {
  const toggle = item.querySelector(".navigation__toggle");
  const controls = toggle?.getAttribute("aria-controls");
  const submenu = controls ? document.getElementById(controls) : null;

  if (!toggle || !submenu) return;

  clearPanelHideTimer(submenu);
  item.classList.toggle("navigation__item--open", isOpen);
  toggle.setAttribute("aria-expanded", isOpen ? "true" : "false");

  if (isOpen) {
    submenu.hidden = false;
    submenu.setAttribute("data-state", "opening");
    setNavigationItemPanelAlignment(item);

    window.requestAnimationFrame(() => {
      setNavigationItemPanelAlignment(item);
      submenu.setAttribute("data-state", "open");
    });

    return;
  }

  item.classList.remove("navigation__item--align-end");
  submenu.setAttribute("data-state", "closing");
  submenu.__hideTimer = window.setTimeout(() => {
    submenu.hidden = true;
    submenu.setAttribute("data-state", "closed");
    clearPanelHideTimer(submenu);
  }, PANEL_TRANSITION_MS);
};

const closeSiblingItems = (item) => {
  const parentList = item.parentElement;
  if (!parentList) return;

  Array.from(parentList.children).forEach((sibling) => {
    if (sibling === item || !(sibling instanceof HTMLElement)) return;
    if (!sibling.classList.contains("navigation__item--has-children")) return;
    setNavigationItemOpen(sibling, false);
  });
};

const setMobileNavigationOpen = (navigation, isOpen) => {
  const toggle = navigation.querySelector(".navigation__mobile-toggle");
  if (!(toggle instanceof HTMLButtonElement)) return;

  navigation.classList.toggle("navigation--mobile-open", isOpen);
  toggle.setAttribute("aria-expanded", isOpen ? "true" : "false");
};

const initHeaderNavigation = (navigation) => {
  const items = getNavigationItems(navigation);

  const updateOpenPanelAlignment = () => {
    items.forEach((item) => {
      if (!item.classList.contains("navigation__item--open")) return;
      setNavigationItemPanelAlignment(item);
    });
  };

  items.forEach((item) => {
    const toggle = item.querySelector(".navigation__toggle");
    const link = item.querySelector(".navigation__link");
    if (!(toggle instanceof HTMLButtonElement)) return;

    setNavigationItemOpen(item, toggle.getAttribute("aria-expanded") === "true");

    toggle.addEventListener("click", () => {
      const isOpen = toggle.getAttribute("aria-expanded") === "true";
      closeSiblingItems(item);
      setNavigationItemOpen(item, !isOpen);
    });

    if (link instanceof HTMLAnchorElement) {
      link.addEventListener("click", (event) => {
        if (
          event.defaultPrevented ||
          event.metaKey ||
          event.ctrlKey ||
          event.shiftKey ||
          event.altKey ||
          event.button !== 0
        ) {
          return;
        }

        const isOpen = toggle.getAttribute("aria-expanded") === "true";
        if (isOpen) return;

        event.preventDefault();
        closeSiblingItems(item);
        setNavigationItemOpen(item, true);
      });
    }

    item.addEventListener("keydown", (event) => {
      if (event.key !== "Escape") return;
      setNavigationItemOpen(item, false);
      toggle.focus();
    });
  });

  document.addEventListener("click", (event) => {
    const target = event.target;
    if (!(target instanceof Node)) return;

    items.forEach((item) => {
      if (item.contains(target)) return;
      setNavigationItemOpen(item, false);
    });
  });

  window.addEventListener("resize", updateOpenPanelAlignment);
};

const initMobileNavigation = (navigation) => {
  const toggle = navigation.querySelector(".navigation__mobile-toggle");
  if (!(toggle instanceof HTMLButtonElement)) return;

  toggle.addEventListener("click", () => {
    const isOpen = toggle.getAttribute("aria-expanded") === "true";
    setMobileNavigationOpen(navigation, !isOpen);
  });

  navigation.querySelectorAll(".navigation__link").forEach((link) => {
    if (!(link instanceof HTMLAnchorElement)) return;
    const item = link.closest(".navigation__item");
    if (item?.classList.contains("navigation__item--has-children")) return;

    link.addEventListener("click", () => {
      setMobileNavigationOpen(navigation, false);
    });
  });

  document.addEventListener("click", (event) => {
    const target = event.target;
    if (!(target instanceof Node)) return;
    if (navigation.contains(target)) return;
    setMobileNavigationOpen(navigation, false);
  });

  navigation.addEventListener("keydown", (event) => {
    if (event.key !== "Escape") return;
    setMobileNavigationOpen(navigation, false);
    toggle.focus();
  });

  const media = window.matchMedia(DESKTOP_NAVIGATION_MEDIA);
  media.addEventListener("change", (event) => {
    if (event.matches) setMobileNavigationOpen(navigation, false);
  });
};

const initNavigation = () => {
  document.querySelectorAll(".navigation--header").forEach((navigation) => {
    if (!(navigation instanceof HTMLElement)) return;
    initHeaderNavigation(navigation);

    if (navigation.dataset.mobileMode === "panel") {
      initMobileNavigation(navigation);
    }
  });
};

initNavigation();
`,
  "search": `(function () {
  var manifestPromise;
  var shardCache = new Map();
  var state = {
    shell: null,
    dialog: null,
    form: null,
    input: null,
    results: null,
    openButtons: [],
    closeButtons: [],
    lastFocusedElement: null,
  };

  function normalize(input) {
    return String(input || "")
      .normalize("NFKD")
      .replace(/[\\u0300-\\u036f]/g, "")
      .toLowerCase()
      .replace(/[^\\p{L}\\p{N}\\s-]+/gu, " ")
      .replace(/-/g, " ")
      .replace(/\\s+/g, " ")
      .trim();
  }

  function tokenize(input) {
    return normalize(input)
      .split(" ")
      .filter(function (token) {
        return token.length > 1;
      });
  }

  function escapeHtml(input) {
    return String(input)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#39;");
  }

  function readJson(path) {
    return fetch(path).then(function (response) {
      if (!response.ok) {
        throw new Error("Search asset request failed: " + path);
      }

      return response.json();
    });
  }

  function getManifest() {
    if (!manifestPromise) {
      manifestPromise = readJson("/assets/search/manifest.json");
    }

    return manifestPromise;
  }

  function getShard(shard) {
    if (!shardCache.has(shard.path)) {
      shardCache.set(shard.path, readJson(shard.path));
    }

    return shardCache.get(shard.path);
  }

  function getLanguageShards(manifest) {
    var currentLanguage = document.documentElement.lang || "en";
    var matching = manifest.shards.filter(function (shard) {
      return shard.language === currentLanguage;
    });

    if (matching.length) return matching;

    return manifest.shards;
  }

  function getMatchingTerms(shard, token) {
    var matches = [];

    Object.keys(shard.terms).forEach(function (term) {
      if (term === token) {
        matches.push({ term: term, factor: 1 });
        return;
      }

      if (term.indexOf(token) === 0) {
        matches.push({ term: term, factor: 0.65 });
      }
    });

    return matches;
  }

  function rankResults(query, shards, limit) {
    var scores = new Map();
    var tokens = tokenize(query);
    var normalizedQuery = normalize(query);

    if (!tokens.length) return [];

    shards.forEach(function (shard) {
      tokens.forEach(function (token) {
        getMatchingTerms(shard, token).forEach(function (match) {
          shard.terms[match.term].forEach(function (posting) {
            var id = posting[0];
            var score = posting[1] * match.factor;
            scores.set(id, (scores.get(id) || 0) + score);
          });
        });
      });
    });

    return Array.from(scores.entries())
      .map(function (entry) {
        var id = entry[0];
        var score = entry[1];
        var documentRecord;

        shards.some(function (shard) {
          if (!shard.docs[id]) return false;
          documentRecord = shard.docs[id];
          return true;
        });

        if (!documentRecord) return null;

        var normalizedTitle = normalize(documentRecord.title);

        if (normalizedTitle === normalizedQuery) score += 40;
        else if (normalizedTitle.indexOf(normalizedQuery) === 0) score += 24;
        else if (normalizedTitle.indexOf(normalizedQuery) >= 0) score += 12;

        return {
          score: score,
          document: documentRecord,
        };
      })
      .filter(Boolean)
      .sort(function (left, right) {
        if (right.score !== left.score) return right.score - left.score;
        return left.document.title.localeCompare(right.document.title);
      })
      .slice(0, limit)
      .map(function (result) {
        return result.document;
      });
  }

  function getScope() {
    if (!state.dialog) return "project";
    return state.dialog.getAttribute("data-search-scope") || "project";
  }

  function getScopePredicate() {
    var scope = getScope();
    var pageId = state.dialog ? state.dialog.getAttribute("data-search-page-id") : "";
    var branch = state.dialog ? state.dialog.getAttribute("data-search-branch") : "";

    if (scope === "page" && pageId) {
      return function (documentRecord) {
        return documentRecord.id === pageId;
      };
    }

    if (scope === "archive" && branch) {
      return function (documentRecord) {
        return documentRecord.branch === branch;
      };
    }

    return function () {
      return true;
    };
  }

  function renderResults(query, results, error) {
    if (!state.results) return;

    if (!normalize(query)) {
      state.results.innerHTML = "";
      state.results.hidden = true;
      return;
    }

    state.results.hidden = false;

    if (error) {
      state.results.innerHTML =
        '<p class="search-results__empty">Search is unavailable right now.</p>';
      return;
    }

    if (!results.length) {
      state.results.innerHTML =
        '<p class="search-results__empty">No results for <strong>' +
        escapeHtml(query) +
        "</strong>.</p>";
      return;
    }

    state.results.innerHTML =
      '<ul class="search-results__list">' +
      results
        .map(function (result) {
          return (
            '<li class="search-results__item">' +
            '<a class="search-results__link" href="' +
            escapeHtml(result.link) +
            '">' +
            '<span class="search-results__title">' +
            escapeHtml(result.title) +
            "</span>" +
            (result.excerpt
              ? '<span class="search-results__excerpt">' +
                escapeHtml(result.excerpt) +
                "</span>"
              : "") +
            "</a>" +
            "</li>"
          );
        })
        .join("") +
      "</ul>";
  }

  function debounce(callback, delay) {
    var timeout;

    return function () {
      var args = arguments;
      var context = this;

      window.clearTimeout(timeout);
      timeout = window.setTimeout(function () {
        callback.apply(context, args);
      }, delay);
    };
  }

  function setOpenState(isOpen) {
    state.openButtons.forEach(function (button) {
      button.setAttribute("aria-expanded", String(isOpen));
    });

    if (state.shell) {
      state.shell.hidden = !isOpen;
      state.shell.classList.toggle("search-shell--open", isOpen);
    }

    document.documentElement.classList.toggle("search-open", isOpen);
    document.body.classList.toggle("search-open", isOpen);
  }

  function openSearch() {
    if (!state.shell || !state.input) return;

    state.lastFocusedElement = document.activeElement;
    setOpenState(true);
    window.requestAnimationFrame(function () {
      state.input.focus();
      state.input.select();
    });
  }

  function closeSearch() {
    if (!state.shell) return;

    setOpenState(false);

    if (
      state.lastFocusedElement &&
      typeof state.lastFocusedElement.focus === "function"
    ) {
      state.lastFocusedElement.focus();
    }
  }

  async function search(query) {
    if (!normalize(query)) {
      renderResults("", []);
      return;
    }

    try {
      var manifest = await getManifest();
      var shards = await Promise.all(
        getLanguageShards(manifest).map(function (descriptor) {
          return getShard(descriptor);
        })
      );
      var allowDocument = getScopePredicate();

      renderResults(
        query,
        rankResults(query, shards, 24)
          .filter(allowDocument)
          .slice(0, 8)
      );
    } catch (_) {
      renderResults(query, [], true);
    }
  }

  function bindEvents() {
    var handleInput = debounce(function () {
      search(state.input.value || "");
    }, 120);

    state.openButtons.forEach(function (button) {
      button.addEventListener("click", openSearch);
    });

    state.closeButtons.forEach(function (button) {
      button.addEventListener("click", closeSearch);
    });

    state.shell.addEventListener("click", function (event) {
      if (event.target === state.shell) {
        closeSearch();
      }
    });

    state.dialog.addEventListener("click", function (event) {
      event.stopPropagation();
    });

    if (state.form) {
      state.form.addEventListener("submit", function (event) {
        event.preventDefault();
        search(state.input.value || "");
      });
    }

    state.input.addEventListener("input", handleInput);
    state.input.addEventListener("search", function () {
      search(state.input.value || "");
    });

    state.results.addEventListener("click", function (event) {
      var target = event.target.closest("a");
      if (!target) return;
      closeSearch();
    });

    document.addEventListener("keydown", function (event) {
      if (!state.shell || state.shell.hidden) {
        if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") {
          event.preventDefault();
          openSearch();
        }
        return;
      }

      if (event.key === "Escape") {
        event.preventDefault();
        closeSearch();
      }
    });
  }

  function initSearch() {
    state.shell = document.querySelector("[data-search-shell]");
    state.dialog = document.querySelector("[data-search-dialog]");
    state.form = document.querySelector("[data-search-form]");
    state.input = document.querySelector("[data-search-input]");
    state.results = document.querySelector("[data-search-results]");
    state.openButtons = Array.prototype.slice.call(
      document.querySelectorAll("[data-search-open]")
    );
    state.closeButtons = Array.prototype.slice.call(
      document.querySelectorAll("[data-search-close]")
    );

    if (!state.shell || !state.dialog || !state.input || !state.results) return;

    bindEvents();
  }

  window.GirkSearch = {
    open: openSearch,
    close: closeSearch,
    search: search,
  };

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", initSearch);
  } else {
    initSearch();
  }
})();
`,
  "stickyNav": `const stickyNav = () => {
  const navigation = document.querySelector(".header__container");
  let ticking = false;
  let lastScrollPosition = 0;

  const setActiveNavigation = (scrollPosition) => {
    if (scrollPosition < 10) {
      navigation.classList.add("header__container--on-top");
      navigation.classList.remove("header__container--off-top");
    } else {
      navigation.classList.remove("header__container--on-top");
      navigation.classList.add("header__container--off-top");
    }
    if (lastScrollPosition > scrollPosition || scrollPosition < 10) {
      navigation.classList.add("header__container--show");
      navigation.classList.remove("header__container--hide");
    } else {
      navigation.classList.add("header__container--hide");
      navigation.classList.remove("header__container--show");
    }
    lastScrollPosition = scrollPosition;
  };

  document.addEventListener("scroll", () => {
    if (!ticking) {
      window.requestAnimationFrame(() => {
        setActiveNavigation(window.scrollY);
        ticking = false;
      });
      ticking = true;
    }
  });
};

stickyNav();`,
  "ui": `const setNavigationOpen = (isOpen) => {
  document.body.classList.toggle("nav-open", isOpen);

  const toggle = document.querySelector(".navigation-toggle");
  if (toggle) {
    toggle.setAttribute("aria-expanded", isOpen ? "true" : "false");
  }
};

const initUi = () => {
  const toggle = document.querySelector(".navigation-toggle");
  const overlay = document.querySelector(".navigation__background");
  const navLinks = document.querySelectorAll(".header .navigation__link");

  if (!toggle) return;

  toggle.addEventListener("click", () => {
    setNavigationOpen(!document.body.classList.contains("nav-open"));
  });

  if (overlay) {
    overlay.addEventListener("click", () => {
      setNavigationOpen(false);
    });
  }

  navLinks.forEach((link) => {
    link.addEventListener("click", () => {
      setNavigationOpen(false);
    });
  });
};

initUi();
`,
  "wrapTables": `const tables = document.querySelectorAll("table");
let initTableWrap = false;

const wrapTables = (tables) => {
  tables &&
    tables.forEach((table) => {
      if (table.getBoundingClientRect().width > window.screen.width) {
        table.classList.add("wrap");
        initTableWrap = true;
      }
    });
};

const labelTables = (tables) => {
  tables &&
    tables.forEach((table) => {
      // Set all headers as attributes to td's
      const headerElements = table.querySelectorAll("thead th");
      const bodyElementRows = table.querySelectorAll("tbody tr");
      const heads = [];

      if (headerElements && bodyElementRows) {
        // Get TH heads
        headerElements.forEach((th) => {
          heads.push(th.textContent);
        });
      }

      if (heads.length) {
        bodyElementRows.forEach((tr) => {
          const tds = tr.querySelectorAll("td");

          tds.forEach((td, i) => {
            td.setAttribute("data-label", heads[i]);
          });
        });
      }
    });
};

wrapTables(tables);
labelTables(tables);

window.addEventListener("resize", () => {
  if (!initTableWrap) wrapTables(tables);
});
`,
};
