import * as fs from "node:fs";
import * as path from "node:path";

// --- Configuration ---
const ROOT = path.resolve(__dirname, "..");
const TEMPLATE_DIR = path.join(ROOT, "src", "template");
const SCRIPT_DIR = path.join(TEMPLATE_DIR, "script");
const OUTPUT_FILE = path.join(ROOT, "src", "libs", "templates", "registry.ts");

const TEMPLATE_EXT = ".ejs";
const SCRIPT_EXT = ".js";

// --- Helpers ---

/** Escape a string so it is safe inside a JS template literal. */
function escapeTemplateLiteral(str: string): string {
  return str
    .replace(/\\/g, "\\\\")   // escape backslashes first
    .replace(/`/g, "\\`")     // escape backticks
    .replace(/\$\{/g, "\\${"); // escape ${ interpolations
}

/** Read and sort all files with the given extension from a directory. */
function readFiles(dir: string, ext: string): Map<string, string> {
  const entries = new Map<string, string>();

  if (!fs.existsSync(dir)) {
    console.warn(`[build-templates] Directory not found: ${dir}`);
    return entries;
  }

  const files = fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(ext))
    .sort();

  for (const file of files) {
    const name = path.basename(file, ext);
    const content = fs.readFileSync(path.join(dir, file), "utf-8");
    entries.set(name, content);
  }

  return entries;
}

/** Build a Record<string, string> block for the generated file. */
function buildRecord(entries: Map<string, string>): string {
  if (entries.size === 0) return "{}";

  const lines: string[] = [];
  for (const [name, content] of entries) {
    const escaped = escapeTemplateLiteral(content);
    lines.push(`  "${name}": \`${escaped}\``);
  }
  return "{\n" + lines.join(",\n") + ",\n}";
}

// --- Main ---

console.log("[build-templates] Reading template files...");

const templates = readFiles(TEMPLATE_DIR, TEMPLATE_EXT);
const scripts = readFiles(SCRIPT_DIR, SCRIPT_EXT);

console.log(
  `  Found ${templates.size} template(s) (${TEMPLATE_EXT}) and ${scripts.size} script(s) (${SCRIPT_EXT})`,
);

const output = [
  "// Auto-generated by scripts/build-templates.ts — DO NOT EDIT",
  "// Regenerate with: npx tsx scripts/build-templates.ts",
  "",
  `export const templates: Record<string, string> = ${buildRecord(templates)};`,
  "",
  `export const scripts: Record<string, string> = ${buildRecord(scripts)};`,
  "",
].join("\n");

fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
fs.writeFileSync(OUTPUT_FILE, output, "utf-8");

console.log(`[build-templates] Written → ${path.relative(ROOT, OUTPUT_FILE)}`);
